#!/bin/bash

[ -f /opt/cnm-sp/wmi-EventLog/pre-install  ] && /opt/cnm-sp/wmi-EventLog/pre-install

/update/db/db-manage.php -p /opt/cnm-sp/wmi-EventLog

if [ -f /opt/cnm-sp/wmi-EventLog/post-install  ]; then
   /opt/cnm-sp/wmi-EventLog/post-install
else exit 0
fi
