#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-EventLog
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-EventLog/pre-install ] && { /opt/cnm-sp/wmi-EventLog/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-EventLog || exit $?

[ -f /opt/cnm-sp/wmi-EventLog/post-install ] && exec /opt/cnm-sp/wmi-EventLog/post-install
exit 0
