<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_cpu_util',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'USO DE CPU EN VM',
            'items' => 'cpuUtil',
            'oid' => '.IID',
            'get_iid' => 'cpuVMID',
            'oidn' => 'cpuUtil.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-RESOURCES-MIB::cpuTable',
            'enterprise' => '0',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_mem_util',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'USO DE MEMORIA EN VM',
            'items' => 'memUtil|memConfigured',
            'oid' => '.IID|.IID',
            'get_iid' => 'memVMID',
            'oidn' => 'memUtil.IID|memConfigured.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-RESOURCES-MIB::memTable',
            'enterprise' => '0',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_disk_util_kb',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'USO DE DISCO EN VM',
            'items' => 'kbRead|kbWritten',
            'oid' => '.IID|.IID',
            'get_iid' => 'hbaName',
            'oidn' => 'kbRead.IID|kbWritten.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-RESOURCES-MIB::vmwHBATable',
            'enterprise' => '0',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_net_util_kb',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'USO DE RED EN VM',
            'items' => 'kbTx|kbRx',
            'oid' => '.IID|.IID',
            'get_iid' => 'netName',
            'oidn' => 'kbTx.IID|kbRx.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-RESOURCES-MIB::vmwNetTable',
            'enterprise' => '0',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_mem_cfg',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'MEMORIA CONFIGURADA EN VM',
            'items' => 'vmwVmMemSize',
            'oid' => '.1.3.6.1.4.1.6876.2.1.1.5.IID',
            'get_iid' => 'vmwVmDisplayName',
            'oidn' => 'vmwVmMemSize.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-VMINFO-MIB::vmwVmTable',
            'enterprise' => '6876',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_vm_status',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'ESTADO DE VM',
            'items' => 'running|notRunning',
            'oid' => '.1.3.6.1.4.1.6876.2.1.1.8.IID',
            'get_iid' => 'vmwVmDisplayName',
            'oidn' => 'vmwVmGuestState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-VMINFO-MIB::vmwVmTable',
            'enterprise' => '6876',
            'esp' => 'MAPS("running")(1,0)|MAPS("notRunning")(0,1)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_vm_glob_status',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'ESTADO GLOBAL DE TODAS LAS VM',
            'items' => 'running|notRunning',
            'oid' => '.1.3.6.1.4.1.6876.2.1.1.8.IID',
            'get_iid' => 'vmwVmDisplayName',
            'oidn' => 'vmwVmGuestState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-VMINFO-MIB::vmwVmTable',
            'enterprise' => '6876',
            'esp' => 'TABLE(MATCH)("running")|TABLE(MATCH)("notRunning")',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'vmware_vm_glob_mem',
            'class' => 'VMWARE',
            'lapse' => '300',
            'descr' => 'MEMORIA GLOBAL DE TODAS LAS VM',
            'items' => 'running|notRunning',
            'oid' => '.1.3.6.1.4.1.6876.2.1.1.8.IID|.1.3.6.1.4.1.6876.2.1.1.5.IID',
            'get_iid' => 'vmwVmDisplayName',
            'oidn' => 'vmwVmGuestState.IID|vmwVmMemSize.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'VMWARE-VMINFO-MIB::vmwVmTable',
            'enterprise' => '6876',
            'esp' => 'TABLE(SUM)("running")|TABLE(SUM)("notRunning")',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'VIRTUAL.VMWARE',
      );


?>
