#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/event-counter
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/event-counter/pre-install ] && { /opt/cnm-sp/event-counter/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/event-counter || exit $?

[ -f /opt/cnm-sp/event-counter/post-install ] && exec /opt/cnm-sp/event-counter/post-install
exit 0
