#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/db-mysqlCmd
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/db-mysqlCmd/pre-install ] && { /opt/cnm-sp/db-mysqlCmd/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/db-mysqlCmd || exit $?

[ -f /opt/cnm-sp/db-mysqlCmd/post-install ] && exec /opt/cnm-sp/db-mysqlCmd/post-install
exit 0
