#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/tcp-connections
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/tcp-connections/pre-install ] && { /opt/cnm-sp/tcp-connections/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/tcp-connections || exit $?

[ -f /opt/cnm-sp/tcp-connections/post-install ] && exec /opt/cnm-sp/tcp-connections/post-install
exit 0
