#!/bin/bash

[ -f /opt/cnm-sp/cnm-device-maintenance/pre-install  ] && /opt/cnm-sp/cnm-device-maintenance/pre-install

if [ -L /opt/cnm/xagent/base/cnm_device_maintenance.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/cnm_device_maintenance.pl
elif [ -e /opt/cnm/xagent/base/cnm_device_maintenance.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/cnm_device_maintenance.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/cnm-device-maintenance/xagent/base/cnm_device_maintenance.pl /opt/cnm/xagent/base/cnm_device_maintenance.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/cnm-device-maintenance

if [ -f /opt/cnm-sp/cnm-device-maintenance/post-install  ]; then
   /opt/cnm-sp/cnm-device-maintenance/post-install
else exit 0
fi
