#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/db-mssqlCmd
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/db-mssqlCmd/pre-install ] && { /opt/cnm-sp/db-mssqlCmd/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/db-mssqlCmd || exit $?

[ -f /opt/cnm-sp/db-mssqlCmd/post-install ] && exec /opt/cnm-sp/db-mssqlCmd/post-install
exit 0
