#!/bin/bash

[ -f /opt/cnm-sp/db-mssqlCmd/pre-install  ] && /opt/cnm-sp/db-mssqlCmd/pre-install

if [ -L /opt/cnm/xagent/base/linux_metric_db_mssqlCmd.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/linux_metric_db_mssqlCmd.pl
elif [ -e /opt/cnm/xagent/base/linux_metric_db_mssqlCmd.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/linux_metric_db_mssqlCmd.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/db-mssqlCmd/xagent/base/linux_metric_db_mssqlCmd.pl /opt/cnm/xagent/base/linux_metric_db_mssqlCmd.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/db-mssqlCmd

if [ -f /opt/cnm-sp/db-mssqlCmd/post-install  ]; then
   /opt/cnm-sp/db-mssqlCmd/post-install
else exit 0
fi
