#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/file-server
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/file-server/pre-install ] && { /opt/cnm-sp/file-server/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/file-server || exit $?

[ -f /opt/cnm-sp/file-server/post-install ] && exec /opt/cnm-sp/file-server/post-install
exit 0
