#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/event-window
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/event-window/pre-install ] && { /opt/cnm-sp/event-window/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/event-window || exit $?

[ -f /opt/cnm-sp/event-window/post-install ] && exec /opt/cnm-sp/event-window/post-install
exit 0
