#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/cfg-monitor
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/cfg-monitor/pre-install ] && { /opt/cnm-sp/cfg-monitor/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/cfg-monitor || exit $?

[ -f /opt/cnm-sp/cfg-monitor/post-install ] && exec /opt/cnm-sp/cfg-monitor/post-install
exit 0
