<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'apc_bat_status',
            'class' => 'APC',
            'lapse' => '300',
            'descr' => 'ESTADO DE LA BATERIA',
            'items' => 'batteryNormal(2)|unknown(1)|batteryInFaultCondition(4)|batteryLow(3)',
            'oid' => '.1.3.6.1.4.1.318.1.1.1.2.1.1.0',
            'get_iid' => '',
            'oidn' => 'PowerNet-MIB::upsBasicBatteryStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PowerNet-MIB::upsBasicBatteryStatus.0',
            'enterprise' => '318',
            'esp' => 'MAP(2)(1,0,0,0)|MAP(1)(0,1,0,0,)|MAP(4)(0,0,1,0,)|MAP(3)(0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.APC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'apc_temperature',
            'class' => 'APC',
            'lapse' => '300',
            'descr' => 'TEMPERATURA INTERNA',
            'items' => 'Temperatura (Celsius)',
            'oid' => '.1.3.6.1.4.1.318.1.1.1.2.2.2.0',
            'get_iid' => '',
            'oidn' => 'PowerNet-MIB::upsAdvBatteryTemperature.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_AREA',
            'vlabel' => 'grados',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PowerNet-MIB::upsAdvBatteryTemperature.0',
            'enterprise' => '318',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.APC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'apc_voltage',
            'class' => 'APC',
            'lapse' => '300',
            'descr' => 'VOLTAJE DE LA BATERIA',
            'items' => 'Voltaje (Voltios)',
            'oid' => '.1.3.6.1.4.1.318.1.1.1.2.2.8.0',
            'get_iid' => '',
            'oidn' => 'PowerNet-MIB::upsAdvBatteryActualVoltage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_AREA',
            'vlabel' => 'volts',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PowerNet-MIB::upsAdvBatteryActualVoltage.0',
            'enterprise' => '318',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.APC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'apc_load',
            'class' => 'APC',
            'lapse' => '300',
            'descr' => 'CARGA DE LA BATERIA',
            'items' => 'Carga de la UPS (%)',
            'oid' => '.1.3.6.1.4.1.318.1.1.1.4.2.3.0',
            'get_iid' => '',
            'oidn' => 'PowerNet-MIB::upsAdvOutputLoad.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_AREA',
            'vlabel' => 'perc',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PowerNet-MIB::upsAdvOutputLoad.0',
            'enterprise' => '318',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.APC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'apc_comm_status',
            'class' => 'APC',
            'lapse' => '300',
            'descr' => 'ESTADO COMUNICACIONES AGENTE UPS',
            'items' => 'ok(1)|noComm(2)',
            'oid' => '.1.3.6.1.4.1.318.1.1.1.8.1.0',
            'get_iid' => '',
            'oidn' => 'PowerNet-MIB::upsCommStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PowerNet-MIB::upsCommStatus.0',
            'enterprise' => '318',
            'esp' => 'MAP(1)(1,0,0,0)|MAP(3)(0,1,0,0,)|MAP(2)(0,0,1,0,)|MAP(4)(0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.APC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'apc_bat_time',
            'class' => 'APC',
            'lapse' => '300',
            'descr' => 'TIEMPO RESTANTE DE LA BATERIA',
            'items' => 'Tiempo restante operativo (min.)',
            'oid' => '.1.3.6.1.4.1.318.1.1.1.2.2.3.0',
            'get_iid' => '',
            'oidn' => 'PowerNet-MIB::upsAdvBatteryRunTimeRemaining.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_AREA',
            'vlabel' => 'min',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PowerNet-MIB::upsAdvBatteryRunTimeRemaining.0',
            'enterprise' => '318',
            'esp' => 'o1/60',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.APC',
      );


?>
