#!/usr/bin/perl -w
#-------------------------------------------------------------------------------------------
# Fichero: install-sp
# Instala todos los SP de /opt/cnm-sp
#-------------------------------------------------------------------------------------------
use strict;
use Getopt::Std;

#-------------------------------------------------------------------------------------------
my @fpth = split ('/',$0,10);
my @fname = split ('\.',$fpth[$#fpth],10);
my $VERSION="1.0";
my $USAGE = <<USAGE;
CNM Support Pack Installer (c) s30labs

$fpth[$#fpth] 
$fpth[$#fpth] -p sp_name
$fpth[$#fpth] -h  : Ayuda

Sin parametros instala todos los Support Packs de /opt/cnm-sp

-p : Permite especificar el nombre de un Support Pack 
-h : Ayuda
USAGE

#-------------------------------------------------------------------------------------------
my %opts=();
getopts("hp:",\%opts);

if ($opts{h}) { die $USAGE;}

my $SP='';
if ($opts{'p'}) { $SP = $opts{'p'}; } 
install_feature($SP);

#-------------------------------------------------------------------------------------------
sub install_feature {
my ($feature) = @_;

   my ($rc,$cmd) = (0,'');
   my $dir_local = ($feature eq '') ? '/opt/cnm-sp' : '/opt/cnm-sp/'.$feature;

   if ($dir_local eq '/opt/cnm-sp') {
      opendir (DIR,$dir_local);
      my @files = readdir(DIR);
      closedir(DIR);
      foreach my $f (@files) {
         if ($f=~/^\./) { next; }
         if ($f=~/^\_/) { next; }
         if (-d "$dir_local/$f") {
            #print "Instalando $f ...\n";
            $cmd = "$dir_local/$f/install";
            if (-f $cmd) {
               $rc = system ($cmd);
               if ($rc !=0) { print "$cmd (rc=$rc)\n"; }
            }
         }
      }
   }
   else {
      $cmd = "$dir_local/install";
      if (-f $cmd) {
         print "Instalando $feature ...\n";
         $rc = system ($cmd);
         if ($rc !=0) { print "$cmd (rc=$rc)\n"; }
      }
		else {
			print STDERR "**ERROR** NO EXISTE $cmd\n";
		}	
   }

}

