#!/bin/bash

[ -f /opt/cnm-sp/wmi-disk/pre-install  ] && /opt/cnm-sp/wmi-disk/pre-install

if [ -L /opt/cnm/xagent/base/linux_metric_wmi_disk.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/linux_metric_wmi_disk.pl
elif [ -e /opt/cnm/xagent/base/linux_metric_wmi_disk.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/linux_metric_wmi_disk.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/wmi-disk/xagent/base/linux_metric_wmi_disk.pl /opt/cnm/xagent/base/linux_metric_wmi_disk.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/wmi-disk

if [ -f /opt/cnm-sp/wmi-disk/post-install  ]; then
   /opt/cnm-sp/wmi-disk/post-install
else exit 0
fi
