#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-disk
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-disk/pre-install ] && { /opt/cnm-sp/wmi-disk/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-disk || exit $?

[ -f /opt/cnm-sp/wmi-disk/post-install ] && exec /opt/cnm-sp/wmi-disk/post-install
exit 0
