#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/vmware-performance
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/vmware-performance/pre-install ] && { /opt/cnm-sp/vmware-performance/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/vmware-performance || exit $?

[ -f /opt/cnm-sp/vmware-performance/post-install ] && exec /opt/cnm-sp/vmware-performance/post-install
exit 0
