#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ssh-syslog
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ssh-syslog/pre-install ] && { /opt/cnm-sp/ssh-syslog/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ssh-syslog || exit $?

[ -f /opt/cnm-sp/ssh-syslog/post-install ] && exec /opt/cnm-sp/ssh-syslog/post-install
exit 0
