<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_cpu_total',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'USO DE CPU TOTAL',
            'items' => 'resCpuUsage.0',
            'oid' => '.1.3.6.1.4.1.5951.4.1.1.41.1.0',
            'get_iid' => '',
            'oidn' => 'NS-ROOT-MIB::resCpuUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::resCpuUsage.0',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_mem_total',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'USO DE MEMORIA TOTAL',
            'items' => 'resMemUsage.0',
            'oid' => '.1.3.6.1.4.1.5951.4.1.1.41.2.0',
            'get_iid' => '',
            'oidn' => 'NS-ROOT-MIB::resMemUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::resMemUsage.0',
            'enterprise' => '5951',
            'esp' => 'INT(o1)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_cpu_usage',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'USO DE CPU',
            'items' => 'nsCPUusage',
            'oid' => '.1.3.6.1.4.1.5951.4.1.1.41.6.1.2.IID',
            'get_iid' => 'nsCPUname',
            'oidn' => 'nsCPUusage.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::nsCPUTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_disk_usage',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'USO DE DISCO',
            'items' => 'sysHealthDiskPerusage',
            'oid' => '.1.3.6.1.4.1.5951.4.1.1.41.8.1.5.IID',
            'get_iid' => 'sysHealthDiskName',
            'oidn' => 'sysHealthDiskPerusage.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::nsSysHealthDiskTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_activity',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'ACTIVIDAD EN VSERVER',
            'items' => 'vsvrTotalRequests|vsvrTotalResponses',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.30.IID|.1.3.6.1.4.1.5951.4.1.3.1.1.32.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrTotalRequests.IID|vsvrTotalResponses.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_traffic',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'TRAFICO EN VSERVER',
            'items' => 'vsvrTotalRequestBytes|vsvrTotalResponseBytes',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.31.IID|.1.3.6.1.4.1.5951.4.1.3.1.1.33.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrTotalRequestBytes.IID|vsvrTotalResponseBytes.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => 'o1*8|o2*8',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_pkts',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'PAQUETES EN VSERVER',
            'items' => 'vsvrTotalPktsSent|vsvrTotalPktsRecvd',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.35.IID|.1.3.6.1.4.1.5951.4.1.3.1.1.34.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrTotalPktsSent.IID|vsvrTotalPktsRecvd.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_cli_tot',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'CLIENTES TOTALES EN VSERVER',
            'items' => 'vsvrTotalClients',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.56.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrTotalClients.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_open_rate',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'TASA DE CONEXIONES EN VSERVER',
            'items' => 'vsvrClientConnOpenRate',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.58.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrClientConnOpenRate.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => 'INT(o1)',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_surge_cnt',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'SURGE COUNT',
            'items' => 'vsvrSurgeCount',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.10.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrSurgeCount.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_health',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'SALUD DEL VSERVER',
            'items' => 'vsvrHealth',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.62.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrHealth.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_health_cnt',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'CONTADOR DE SALUD',
            'items' => 'vsvrHealth',
            'oid' => '.1.3.6.1.4.1.5951.4.1.1.41.7.1.2.IID',
            'get_iid' => 'sysHealthCounterName',
            'oidn' => 'sysHealthCounterValue.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'NS-ROOT-MIB::nsSysHealthTable',
            'enterprise' => '5951',
            'esp' => '',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCALER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'netscaler_vsvr_status',
            'class' => 'NETSCALER',
            'lapse' => '300',
            'descr' => 'ESTADO DEL VSERVER',
            'items' => 'up(7)|down(1)|unknown(2)|busy(3)|outOfService(4)|transitionToOutOfService(5)|transitionToOutOfServiceDown(8)',
            'oid' => '.1.3.6.1.4.1.5951.4.1.3.1.1.5.IID',
            'get_iid' => 'vsvrName',
            'oidn' => 'vsvrState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'Status',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NS-ROOT-MIB::vserverTable',
            'enterprise' => '5951',
            'esp' => 'MAP(7)(1,0,0,0,0,0,0,0)|MAP(1)(0,1,0,0,0,0,0,0)|MAP(2)(0,0,1,0,0,0,0,0)|MAP(3)(0,0,0,1,0,0,0,0)|MAP(4)(0,0,0,0,1,0,0,0)|MAP(5)(0,0,0,0,0,1,0,0)|MAP(6)(0,0,0,0,0,0,1,0)|MAP(8)(0,0,0,0,0,0,0,1)',
            'params' => '[{"key":"iid_mode","value":"ascii"}]',
            'itil_type' => '4',
            'apptype' => 'NET.NETSCALER',
      );


?>
