#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-perfOS
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-perfOS/pre-install ] && { /opt/cnm-sp/wmi-perfOS/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-perfOS || exit $?

[ -f /opt/cnm-sp/wmi-perfOS/post-install ] && exec /opt/cnm-sp/wmi-perfOS/post-install
exit 0
