#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ENT_21796_HWGROUP
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ENT_21796_HWGROUP/pre-install ] && { /opt/cnm-sp/ENT_21796_HWGROUP/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ENT_21796_HWGROUP || exit $?

[ -f /opt/cnm-sp/ENT_21796_HWGROUP/post-install ] && exec /opt/cnm-sp/ENT_21796_HWGROUP/post-install
exit 0
