#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ssh-docker
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ssh-docker/pre-install ] && { /opt/cnm-sp/ssh-docker/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ssh-docker || exit $?

[ -f /opt/cnm-sp/ssh-docker/post-install ] && exec /opt/cnm-sp/ssh-docker/post-install
exit 0
