#!/bin/bash

[ -f /opt/cnm-sp/wmi-services/pre-install  ] && /opt/cnm-sp/wmi-services/pre-install

/update/db/db-manage.php -p /opt/cnm-sp/wmi-services

if [ -f /opt/cnm-sp/wmi-services/post-install  ]; then
   /opt/cnm-sp/wmi-services/post-install
else exit 0
fi
