#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-services
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-services/pre-install ] && { /opt/cnm-sp/wmi-services/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-services || exit $?

[ -f /opt/cnm-sp/wmi-services/post-install ] && exec /opt/cnm-sp/wmi-services/post-install
exit 0
