#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-class
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-class/pre-install ] && { /opt/cnm-sp/wmi-class/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-class || exit $?

[ -f /opt/cnm-sp/wmi-class/post-install ] && exec /opt/cnm-sp/wmi-class/post-install
exit 0
