#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ENT_34225_CNM
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ENT_34225_CNM/pre-install ] && { /opt/cnm-sp/ENT_34225_CNM/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ENT_34225_CNM || exit $?

[ -f /opt/cnm-sp/ENT_34225_CNM/post-install ] && exec /opt/cnm-sp/ENT_34225_CNM/post-install
exit 0
