#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-pagefileusage
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-pagefileusage/pre-install ] && { /opt/cnm-sp/wmi-pagefileusage/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-pagefileusage || exit $?

[ -f /opt/cnm-sp/wmi-pagefileusage/post-install ] && exec /opt/cnm-sp/wmi-pagefileusage/post-install
exit 0
