#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/apache-mod_status
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/apache-mod_status/pre-install ] && { /opt/cnm-sp/apache-mod_status/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/apache-mod_status || exit $?

[ -f /opt/cnm-sp/apache-mod_status/post-install ] && exec /opt/cnm-sp/apache-mod_status/post-install
exit 0
