#!/usr/bin/perl -w
#-------------------------------------------------------------------------------------------
# Fichero: install
# Instalacion idioma en
#-------------------------------------------------------------------------------------------
use strict;
use Getopt::Std;

#-------------------------------------------------------------------------------------------
my $LANG='en';
my $SP='apache-mod_status';

#-------------------------------------------------------------------------------------------
my $BASE_DIR="/opt/cnm-sp/$SP/lang/$LANG";
my $LOGGER='/usr/bin/logger -p local0.info';

#-------------------------------------------------------------------------------------------
print "***> INSTALANDO IDIOMA [$LANG] EN SP $SP ....\n";
my $cmd = "/update/db/db-manage.php -p $BASE_DIR";
my $rc = system ("$cmd");
my $extra='';
if ($rc != 0) { $extra='**ERROR**'; }
system ("$LOGGER -- INSTALANDO IDIOMA [$LANG] EN SP $SP $0 [$cmd] rc=$rc $extra");
