#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/event-data
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/event-data/pre-install ] && { /opt/cnm-sp/event-data/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/event-data || exit $?

[ -f /opt/cnm-sp/event-data/post-install ] && exec /opt/cnm-sp/event-data/post-install
exit 0
