#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ENT_00318_APC
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ENT_00318_APC/pre-install ] && { /opt/cnm-sp/ENT_00318_APC/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ENT_00318_APC || exit $?

[ -f /opt/cnm-sp/ENT_00318_APC/post-install ] && exec /opt/cnm-sp/ENT_00318_APC/post-install
exit 0
