#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/www-base
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/www-base/pre-install ] && { /opt/cnm-sp/www-base/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/www-base || exit $?

[ -f /opt/cnm-sp/www-base/post-install ] && exec /opt/cnm-sp/www-base/post-install
exit 0
