#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/sp-scheme
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/sp-scheme/pre-install ] && { /opt/cnm-sp/sp-scheme/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/sp-scheme || exit $?

[ -f /opt/cnm-sp/sp-scheme/post-install ] && exec /opt/cnm-sp/sp-scheme/post-install
exit 0
