#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ENT_13191_ONEACCESS
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ENT_13191_ONEACCESS/pre-install ] && { /opt/cnm-sp/ENT_13191_ONEACCESS/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ENT_13191_ONEACCESS || exit $?

[ -f /opt/cnm-sp/ENT_13191_ONEACCESS/post-install ] && exec /opt/cnm-sp/ENT_13191_ONEACCESS/post-install
exit 0
