#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-RDSCfg
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-RDSCfg/pre-install ] && { /opt/cnm-sp/wmi-RDSCfg/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-RDSCfg || exit $?

[ -f /opt/cnm-sp/wmi-RDSCfg/post-install ] && exec /opt/cnm-sp/wmi-RDSCfg/post-install
exit 0
