#!/bin/bash

[ -f /opt/cnm-sp/wmi-RDSCfg/pre-install  ] && /opt/cnm-sp/wmi-RDSCfg/pre-install

if [ -L /opt/cnm/xagent/base/linux_metric_wmi_RDSCfg.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/linux_metric_wmi_RDSCfg.pl
elif [ -e /opt/cnm/xagent/base/linux_metric_wmi_RDSCfg.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/linux_metric_wmi_RDSCfg.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/wmi-RDSCfg/xagent/base/linux_metric_wmi_RDSCfg.pl /opt/cnm/xagent/base/linux_metric_wmi_RDSCfg.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/wmi-RDSCfg

if [ -f /opt/cnm-sp/wmi-RDSCfg/post-install  ]; then
   /opt/cnm-sp/wmi-RDSCfg/post-install
else exit 0
fi
