#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/tcp-check
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/tcp-check/pre-install ] && { /opt/cnm-sp/tcp-check/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/tcp-check || exit $?

[ -f /opt/cnm-sp/tcp-check/post-install ] && exec /opt/cnm-sp/tcp-check/post-install
exit 0
