#!/bin/bash

[ -f /opt/cnm-sp/tcp-check/pre-install  ] && /opt/cnm-sp/tcp-check/pre-install

if [ -L /opt/cnm/xagent/base/linux_metric_tcp_check.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/linux_metric_tcp_check.pl
elif [ -e /opt/cnm/xagent/base/linux_metric_tcp_check.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/linux_metric_tcp_check.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/tcp-check/xagent/base/linux_metric_tcp_check.pl /opt/cnm/xagent/base/linux_metric_tcp_check.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/tcp-check

if [ -f /opt/cnm-sp/tcp-check/post-install  ]; then
   /opt/cnm-sp/tcp-check/post-install
else exit 0
fi
