#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ssl-url-cert
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ssl-url-cert/pre-install ] && { /opt/cnm-sp/ssl-url-cert/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ssl-url-cert || exit $?

[ -f /opt/cnm-sp/ssl-url-cert/post-install ] && exec /opt/cnm-sp/ssl-url-cert/post-install
exit 0
