#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ipmi-sensors
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ipmi-sensors/pre-install ] && { /opt/cnm-sp/ipmi-sensors/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ipmi-sensors || exit $?

[ -f /opt/cnm-sp/ipmi-sensors/post-install ] && exec /opt/cnm-sp/ipmi-sensors/post-install
exit 0
