#!/usr/bin/perl -w
#--------------------------------------------------------------------------------------
# NAME:  apache_mod_status-check
#
# DESCRIPTION:
# Obtiene metricas a del Servidor WEB Apache a partir del modulo mod_status.
#
# CALLING SAMPLE:
# apache_mod_status-check -n 1.1.1.1
#
# INPUT (PARAMS):
# a. -n  :  IP remota
#
# OUTPUT (STDOUT):
#<001> Parents = 0
#<002> Requests = 1
#<003> Idle workers = 5
#<004> Waiting for Connection = 5
#<005> Starting up = 0
#<006> Reading Request = 0
#<007> Sending Reply = 1
#<008> Keepalive (read) = 0
#<009> DNS Lookup = 0
#<010> Closing connection = 0
#<011> Logging = 0
#<012> Gracefully finishing = 0
#<013> Idle cleanup of worker = 0
#<014> Open slot with no current process = 250
#<015> Total accesses = 2503
#<016> Total traffic = 433 kB
#<017> Requests per second = .0295
#<018> Bytes per second = 5
#<019> Bytes per request = 177

#
# OUTPUT (STDERR):
# Error info, warnings etc... If verbose also debug info.
#
# EXIT CODE:
#  0: OK
# -1: System error
# >0: Script error
#--------------------------------------------------------------------------------------
use lib '/opt/crawler/bin/';
use Getopt::Std;
use Parse::Apache::ServerStatus;
use Data::Dumper;

#-------------------------------------------------------------------------------------------
my %opts=();
my $USAGE="Uso: $0 -n ip [-s]";
getopts("hsn:",\%opts);

#-------------------------------------------------------------------------------------------
if (exists $opts{h}) { die "$USAGE\n"; }
if (! exists $opts{n}) { die "$USAGE\n"; }

#-------------------------------------------------------------------------------------------
my $URI='http:';
if ($opts{s}) { $URI='https:'; }
my $URL=$URI.'//'.$opts{n}.'/server-status';

$|++;
my $prs = Parse::Apache::ServerStatus->new( url =>$URL, timeout => 5);

my $stat = $prs->get();
my $rc=0;
if (defined $stat) { $rc=1; }
print "$rc\n";

