#!/usr/bin/perl -w
#--------------------------------------------------------------------------------------
# NAME:  wmi-check
#
# DESCRIPTION:
# Obtiene valores de los contadores WMI de un equipo WIndows remoto
#
# CALLING SAMPLE:
# wmi-check -n 1.1.1.1 -d dominio -u user -p pwd  [-v]
# wmi-check -h  : Ayuda
#
# INPUT (PARAMS):
# a. -n  :  IP remota
# b. -d  :  Dominio
# c. -u  :  Usuario WMI
# d. -p  :  Clave
# e. -c  :  Clase wmi
# f. -i  :  Indice (iid) para la Clase wmi (Si aplica)
#
# OUTPUT (STDOUT):
# <200.ALG> State = 3
# <200.AeLookupSvc> State = 3
# <200.AppIDSvc> State = 3
# <200.AppMgmt> State = 3
# <200.Appinfo> State = 1
# ...
#
# OUTPUT (STDERR):
# Error info, warnings etc... If verbose also debug info.
#
# EXIT CODE:
#  0: OK
# -1: System error
# >0: Script error
#--------------------------------------------------------------------------------------
use lib '/opt/crawler/bin/';
use strict;
use Getopt::Std;
use Data::Dumper;
use Stdout;
use CNMScripts::WMI;

#--------------------------------------------------------------------------------------
my $counters;

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------
my @fpth = split ('/',$0,10);
my @fname = split ('\.',$fpth[$#fpth],10);
my $VERSION="1.0";

my $USAGE = <<USAGE;
wmi-check $VERSION

$fpth[$#fpth] -n IP -u user -p pwd [-d domain] [-i Name]
$fpth[$#fpth] -n IP -u domain/user -p pwd [-i Name]
$fpth[$#fpth] -h  : Ayuda

-n    IP remota
-u    user
-p    pwd
-d    Dominio
-i    Index Propiedad para indexar las instancias. Por defecto es Name.
-h    Ayuda
-v    Verbose

$fpth[$#fpth] -n 1.1.1.1 -u user -p xxx
$fpth[$#fpth] -n 1.1.1.1 -u user -p xxx -d miDominio
$fpth[$#fpth] -n 1.1.1.1 -u user -p xxx -i Name
USAGE

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------
my %opts=();
getopts("hvn:u:p:d:c:i:",\%opts);

if ($opts{h}) { die $USAGE;}
my $ip = $opts{n} || die $USAGE;
my $user = $opts{u} || die $USAGE;
my $pwd = $opts{p} || die $USAGE;
my $domain='';
if ($user=~/(\S+)\/(\S+)/) { $user = $1; $domain = $2; }

#my $property_index = 'Name';
my $property_index = '';
if (exists $opts{i}) {$property_index = $opts{i}; }

#--------------------------------------------------------------------------------------
my $rc=0;
my $wmi = CNMScripts::WMI->new('host'=>$ip, 'user'=>$user, 'pwd'=>$pwd, 'domain'=>$domain);

my $ok=$wmi->check_tcp_port($ip,'135',5);
if ($ok) { 

	$counters = $wmi->get_wmi_counters("'SELECT OSType FROM Win32_OperatingSystem'", $property_index);
	if (exists $counters->[0]->{'OSType'}) { $rc=1; }
}
print "$rc\n";
#print Dumper($counters);


