#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/vmware-vminfo
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/vmware-vminfo/pre-install ] && { /opt/cnm-sp/vmware-vminfo/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/vmware-vminfo || exit $?

[ -f /opt/cnm-sp/vmware-vminfo/post-install ] && exec /opt/cnm-sp/vmware-vminfo/post-install
exit 0
