#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ssh-linuxSysstats
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ssh-linuxSysstats/pre-install ] && { /opt/cnm-sp/ssh-linuxSysstats/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ssh-linuxSysstats || exit $?

[ -f /opt/cnm-sp/ssh-linuxSysstats/post-install ] && exec /opt/cnm-sp/ssh-linuxSysstats/post-install
exit 0
