#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/www-status
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/www-status/pre-install ] && { /opt/cnm-sp/www-status/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/www-status || exit $?

[ -f /opt/cnm-sp/www-status/post-install ] && exec /opt/cnm-sp/www-status/post-install
exit 0
