#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-process
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-process/pre-install ] && { /opt/cnm-sp/wmi-process/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-process || exit $?

[ -f /opt/cnm-sp/wmi-process/post-install ] && exec /opt/cnm-sp/wmi-process/post-install
exit 0
