#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/wmi-RDSLicenses
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/wmi-RDSLicenses/pre-install ] && { /opt/cnm-sp/wmi-RDSLicenses/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/wmi-RDSLicenses || exit $?

[ -f /opt/cnm-sp/wmi-RDSLicenses/post-install ] && exec /opt/cnm-sp/wmi-RDSLicenses/post-install
exit 0
