#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ssl-certs
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ssl-certs/pre-install ] && { /opt/cnm-sp/ssl-certs/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ssl-certs || exit $?

[ -f /opt/cnm-sp/ssl-certs/post-install ] && exec /opt/cnm-sp/ssl-certs/post-install
exit 0
