#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ssh-linuxOS
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ssh-linuxOS/pre-install ] && { /opt/cnm-sp/ssh-linuxOS/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ssh-linuxOS || exit $?

[ -f /opt/cnm-sp/ssh-linuxOS/post-install ] && exec /opt/cnm-sp/ssh-linuxOS/post-install
exit 0
