#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ldap-auth
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ldap-auth/pre-install ] && { /opt/cnm-sp/ldap-auth/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ldap-auth || exit $?

[ -f /opt/cnm-sp/ldap-auth/post-install ] && exec /opt/cnm-sp/ldap-auth/post-install
exit 0
