#!/bin/bash

[ -f /opt/cnm-sp/ldap-auth/pre-install  ] && /opt/cnm-sp/ldap-auth/pre-install

if [ -L /opt/cnm/xagent/base/linux_metric_ldap_auth.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/linux_metric_ldap_auth.pl
elif [ -e /opt/cnm/xagent/base/linux_metric_ldap_auth.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/linux_metric_ldap_auth.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/ldap-auth/xagent/base/linux_metric_ldap_auth.pl /opt/cnm/xagent/base/linux_metric_ldap_auth.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/ldap-auth

if [ -f /opt/cnm-sp/ldap-auth/post-install  ]; then
   /opt/cnm-sp/ldap-auth/post-install
else exit 0
fi
