#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/t
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/t/pre-install ] && { /opt/cnm-sp/t/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/t || exit $?

[ -f /opt/cnm-sp/t/post-install ] && exec /opt/cnm-sp/t/post-install
exit 0
