#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/mail-mbox
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/mail-mbox/pre-install ] && { /opt/cnm-sp/mail-mbox/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/mail-mbox || exit $?

[ -f /opt/cnm-sp/mail-mbox/post-install ] && exec /opt/cnm-sp/mail-mbox/post-install
exit 0
