#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/api-device
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/api-device/pre-install ] && { /opt/cnm-sp/api-device/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/api-device || exit $?

[ -f /opt/cnm-sp/api-device/post-install ] && exec /opt/cnm-sp/api-device/post-install
exit 0
