#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ENT_06876_VMWARE
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ENT_06876_VMWARE/pre-install ] && { /opt/cnm-sp/ENT_06876_VMWARE/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ENT_06876_VMWARE || exit $?

[ -f /opt/cnm-sp/ENT_06876_VMWARE/post-install ] && exec /opt/cnm-sp/ENT_06876_VMWARE/post-install
exit 0
