#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/ENT_02021_UCDAVIS
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/ENT_02021_UCDAVIS/pre-install ] && { /opt/cnm-sp/ENT_02021_UCDAVIS/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/ENT_02021_UCDAVIS || exit $?

[ -f /opt/cnm-sp/ENT_02021_UCDAVIS/post-install ] && exec /opt/cnm-sp/ENT_02021_UCDAVIS/post-install
exit 0
