#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/event-status
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/event-status/pre-install ] && { /opt/cnm-sp/event-status/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/event-status || exit $?

[ -f /opt/cnm-sp/event-status/post-install ] && exec /opt/cnm-sp/event-status/post-install
exit 0
