#!/bin/bash

[ -f /opt/cnm-sp/icmp-dual/pre-install  ] && /opt/cnm-sp/icmp-dual/pre-install

if [ -L /opt/cnm/xagent/base/linux_metric_icmp_dual.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/linux_metric_icmp_dual.pl
elif [ -e /opt/cnm/xagent/base/linux_metric_icmp_dual.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/linux_metric_icmp_dual.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/icmp-dual/xagent/base/linux_metric_icmp_dual.pl /opt/cnm/xagent/base/linux_metric_icmp_dual.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/icmp-dual

if [ -f /opt/cnm-sp/icmp-dual/post-install  ]; then
   /opt/cnm-sp/icmp-dual/post-install
else exit 0
fi
