#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/icmp-dual
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/icmp-dual/pre-install ] && { /opt/cnm-sp/icmp-dual/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/icmp-dual || exit $?

[ -f /opt/cnm-sp/icmp-dual/post-install ] && exec /opt/cnm-sp/icmp-dual/post-install
exit 0
