#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/api-inventory
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/api-inventory/pre-install ] && { /opt/cnm-sp/api-inventory/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/api-inventory || exit $?

[ -f /opt/cnm-sp/api-inventory/post-install ] && exec /opt/cnm-sp/api-inventory/post-install
exit 0
