#!/bin/bash
#-------------------------------------------------------------------------------------------
# Instalacion del plugin /opt/cnm-sp/cnm-backup-put
#-------------------------------------------------------------------------------------------

[ -f /opt/cnm-sp/cnm-backup-put/pre-install ] && { /opt/cnm-sp/cnm-backup-put/pre-install || exit $?; }

/update/db/db-manage.php -p /opt/cnm-sp/cnm-backup-put || exit $?

[ -f /opt/cnm-sp/cnm-backup-put/post-install ] && exec /opt/cnm-sp/cnm-backup-put/post-install
exit 0
