#!/bin/bash

[ -f /opt/cnm-sp/cnm-backup-put/pre-install  ] && /opt/cnm-sp/cnm-backup-put/pre-install

if [ -L /opt/cnm/xagent/base/cnm_backup_put.pl  ]; then
   /bin/rm -f /opt/cnm/xagent/base/cnm_backup_put.pl
elif [ -e /opt/cnm/xagent/base/cnm_backup_put.pl  ]; then
   /bin/mv /opt/cnm/xagent/base/cnm_backup_put.pl /tmp
elif [ -d /opt/cnm/xagent/base  ]; then
	/bin/ln -s /opt/cnm-sp/cnm-backup-put/xagent/base/cnm_backup_put.pl /opt/cnm/xagent/base/cnm_backup_put.pl
fi
/update/db/db-manage.php -p /opt/cnm-sp/cnm-backup-put

if [ -f /opt/cnm-sp/cnm-backup-put/post-install  ]; then
   /opt/cnm-sp/cnm-backup-put/post-install
else exit 0
fi
